config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations' }, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  devise_scope :user do
    authenticated :user do
      root 'users#show', as: :authenticated_root
    end

    unauthenticated do
      root 'users#signup', as: :unauthenticated_root
    end
  end

  resources :users, only: [:show]

  resources :registered_applications

  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#create', via: [:options]
    resources :events, only: [:create]
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :registered_application
end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
  belongs_to :user
  has_many :events, dependent: :destroy

  validates :name, presence: true
  validates :url, presence: true, uniqueness: true
  validates_format_of :url, with: URI::regexp(%w(http https))
end

app/models/user.rb
class User < ActiveRecord::Base
  # Other available devise modules are:
  # :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable

  has_many :registered_applications, dependent: :destroy

  def admin?
    role == 'admin'
  end
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_filter :cors_preflight_check
  after_filter :set_access_control_headers

  def create
    registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])
    
    if !registered_application
      render json: "Unregistered application", status: :unprocessable_entity
    else
      @event = registered_application.events.build(event_params)

      if @event.save
        render json: @event, status: :created
      else
        render json: @event.errors, status: :unprocessable_entity
      end
    end
  end

private
  def event_params
    params.permit(:name)
  end

  # CORS
  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Access-Control-Allow-Origin, Content-Type'
  end

  # CORS preflight sanity checks client/server to allow legacy servers to support CORS
  def cors_preflight_check
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Access-Control-Allow-Origin, X-Requested-With, X-Prototype-Version, Content-Type'
    headers['Access-Control-Max-Age'] = '1728000'
    render text: "" if request.method == "OPTIONS"
  end
  # curl -v -H "Accept: application/json" -H "Origin: http://localhost:3000" --header "Content-type: application/json" -X POST -d '{"name":"foo"}'  http://localhost:9000/api/events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << [:name, :email]
  end
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  before_action :set_application, except: [:index, :new, :create]

  def index
    @registered_applications = current_user.registered_applications.all
  end

  def show
    @events = @registered_application.events.group_by(&:name)
  end

  def new
    @registered_application = current_user.registered_applications.new
  end

  def create
    @registered_application = current_user.registered_applications.build(registered_application_params)
    if @registered_application.save
      redirect_to @registered_application, notice: 'Application registered!'
    else
      flash[:error] = @registered_application.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
  end

  def update
    if @registered_application.update_attributes(registered_application_params)
      redirect_to @registered_application, notice: 'Application updated!'
    else
      flash[:error] = 'Oops! try again.'
      render :edit
    end
  end

  def destroy
    if @registered_application.destroy
      redirect_to current_user, notice: 'Application removed!'
    else
      redirect_to :back, error: 'Oops! try again.'
    end
  end

private

  def set_application
     @registered_application = current_user.registered_applications.find(params[:id])
  end

  def registered_application_params
    params.require(:registered_application).permit(:name, :url)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def update
    account_update_params = devise_parameter_sanitizer.sanitize(:account_update)
    @user = User.find(current_user.id)

    if needs_password?
      successfully_updated = @user.update_with_password(account_update_params)
    else
      account_update_params.delete('password')
      account_update_params.delete('password_confirmation')
      account_update_params.delete('current_password')
      successfully_updated = @user.update_attributes(account_update_params)
    end

    if successfully_updated
      set_flash_message :notice, :updated
      sign_in @user, :bypass => true
      redirect_to edit_user_registration_path
    else
      render 'edit'
    end
  end

  private

  def needs_password?
    @user.email != params[:user][:email] || params[:user][:password].present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def signup
    render template: "devise/registrations/new"
  end

  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # devise for other controllers
  def resource_name
    @resource_name ||= admin_controller? ? :admin_user : :user
  end

  def resource
    @resource ||= resource_name.to_s.classify.constantize.new
  end

  def resource_class
    devise_mapping.to
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[resource_name]
  end

  def admin_controller?
    !devise_controller? && request.path =~ /^\/admin/
  end

  def bootstrap_devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-block">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <h5>#{sentence}</h5>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def bootstrap_flash(flash)
    return if flash.empty?
    
    key = flash.keys.first
    type = case key
    when "notice"; "success"
    when "error"; "danger"
    else "warning"
    end

    html = <<-HTML
    <div class="alert alert-#{type}">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      #{flash[:"#{key}"]}
    </div>
    HTML

    html.html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= ENV['APP_NAME'] %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  <%= yield :head %>
</head>
<body>
  <div class="container">
    <%= bootstrap_flash flash %>
    <div class="pull-right user-info">
      <% if current_user %>
        Hello <%= link_to current_user.name, current_user %>!
        <%= link_to edit_user_registration_path, class: 'btn btn-primary btn-sm' do %>
          <span class="glyphicon glyphicon-user"></span>
        <% end %>
        <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-sm' do %>
          <span class="glyphicon glyphicon-log-out"></span>
        <% end %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path %> or
        <%= link_to "Sign Up", new_user_registration_path %>
      <% end %>
    </div>
    
    <%= yield %>
  </div>
</body>
</html>

app/views/registered_applications/_registered_application.html.erb
<div class="row">
  <h4><%= link_to registered_application.name, registered_application %></h4>
  <%= link_to registered_application.url, registered_application.url, target: '_blank' %>
</div>

app/views/registered_applications/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4><%= t('.application_update', default: 'Update Application') %></h4>
  </div>
  <div class="panel-body">
    <%= form_for @registered_application do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :url %>
        <%= f.text_field :url, class: 'form-control' %>
      </div>
      <%= f.submit t('.application_edit', default: 'Update application'), class: 'btn btn-default' %>
    <% end %>
  </div>
</div>

app/views/registered_applications/index.html.erb
<%= render @registered_applications %>

app/views/registered_applications/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4><%= t('.application_register', default: 'Register Application') %></h4>
  </div>
  <div class="panel-body">
    <%= form_for @registered_application do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :url %>
        <%= f.text_field :url, class: 'form-control' %>
      </div>
      <%= f.submit t('.application_create', default: 'Register application'), class: 'btn btn-default' %>
    <% end %>
  </div>
</div>

app/views/registered_applications/show.html.erb
<% content_for :head do %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<% end %>
<h2>
  <%= @registered_application.name %>
  <small>
    <%= link_to 'Edit', edit_registered_application_path %> |
    <%= link_to 'Delete', @registered_application, method: :delete, data: {confirm: 'Delete application?'} %>
  </small>
</h2>
<%= link_to @registered_application.url, @registered_application.url, target: '_blank' %>

<ul class="events">
<% @events.each do |name, events| %>
  <li><%= "#{name} [#{events.count} #{'event'.pluralize(events.count)}]" %></li>
<% end %>
</ul>
<%= pie_chart @registered_application.events.group(:name).count %>

<%= line_chart @registered_application.events.group_by_day(:created_at).count %>

app/views/shared/_flash.html.erb
<%= bootstrap_flash flash %>

app/views/users/show.html.erb
<div class="well well-lg">
  <h4><%= @user.name %> <small><%= link_to 'Edit', edit_user_registration_path %></small></h4>
  <h6><%= @user.email %></h6>
  <%= link_to registered_applications_path, class: 'btn btn-default' do %>
      <i class="glyphicon glyphicon-th-list"></i>&nbsp; My Applications
    <% end %>
  <%= link_to new_registered_application_path, class: 'btn btn-default' do %>
    <i class="glyphicon glyphicon-plus"></i>&nbsp; Add application
  <% end %>
</div>